# Generated by Django 5.0.1 on 2024-04-23 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="messages",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="messages",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
